In [5]:
import torch
a = torch.tensor(
    [[1,2,3],
     [4,5,6]],
    dtype=torch.int32
)
print(a)
print(a.shape) 
print("Số chiều :", a.ndim)  
print("Kiểu dữ liệu:", a.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
torch.Size([2, 3])
Số chiều : 2
Kiểu dữ liệu: torch.int32


In [3]:
import torch

a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)

print("a:", a)
print("b:", b)
print("c:", c)
print("d:", d)
print("e:", e)

f = torch.full((5, 5), 10) 
print("f:\n", f)

a: tensor([[0.7836, 0.5371, 0.6093, 0.2076],
        [0.0325, 0.3775, 0.0851, 0.5707],
        [0.7987, 0.7892, 0.1755, 0.4664]])
b: tensor([[ 1.1224, -0.0537, -0.3625,  1.1995],
        [-1.0127, -1.3238, -0.1649,  0.0611],
        [-1.2091, -0.0568,  1.2723,  1.0078]])
c: tensor([[0., 0., 0.],
        [0., 0., 0.]])
d: tensor([[1., 1., 1.],
        [1., 1., 1.]])
e: tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
f:
 tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


In [4]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


In [5]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[-0.0597,  1.2278,  0.9408,  0.5593, -0.6851],
         [-0.2243, -0.8721,  2.5682, -0.7974, -1.1751],
         [ 1.3588,  0.5322,  0.8183, -0.3485,  1.1361],
         [ 0.7370,  0.4983,  0.1531, -0.8623, -0.6487]],

        [[-0.1281,  2.1224,  0.8175, -0.8429, -0.8531],
         [ 0.5063,  0.1790,  0.7007, -0.1818,  1.5648],
         [ 0.2706,  0.8438,  0.6965, -0.9088, -1.0394],
         [-0.7126,  0.9287,  0.0389, -0.4884, -0.1076]],

        [[ 0.2818,  0.6012, -2.1709, -1.7410,  0.5484],
         [-0.9650, -2.2536,  0.1958,  1.1613, -0.0807],
         [ 0.0798, -0.1494,  0.2809,  0.7868,  0.2482],
         [-1.4259,  0.3945,  0.1963, -3.8691, -0.9645]]])

Tensor a[1]:
tensor([[-0.1281,  2.1224,  0.8175, -0.8429, -0.8531],
        [ 0.5063,  0.1790,  0.7007, -0.1818,  1.5648],
        [ 0.2706,  0.8438,  0.6965, -0.9088, -1.0394],
        [-0.7126,  0.9287,  0.0389, -0.4884, -0.1076]])

Tensor a[1:, 2:4]:
tensor([[[ 0.2706,  0.8438,  0.6965, -0.9088, -1.0

In [6]:
import torch

a = torch.randn(3, 4, 5)

print("Original tensor:")
print(a)

print("\nTensor a[1]:")
print(a[1])

print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

print("\nShape của a[1]:", a[1].shape) 
print("Shape của a[1:, 2:4]:", a[1:, 2:4].shape) 

two_last_elements = a[:, :, -2:]
print("\nHai phần tử cuối cùng trên chiều thứ ba:")
print(two_last_elements)

Original tensor:
tensor([[[-0.2211,  0.4329,  1.0596, -1.7404, -0.5545],
         [ 0.7415, -0.4235,  1.9527, -0.5833,  0.3552],
         [-1.2974,  0.6274,  0.0394,  0.7790, -0.3062],
         [-0.6134, -0.7373,  0.6305, -1.5295, -0.6019]],

        [[-1.2622, -0.8485, -0.2482, -0.6014, -0.3126],
         [-0.2190,  0.9474,  0.7915,  0.4334, -0.5306],
         [ 0.3472,  0.6003, -0.5783,  1.1203, -2.4669],
         [ 0.6066, -1.1424,  0.0438, -0.0313, -0.7336]],

        [[-0.8765, -0.7716,  0.6714, -1.3731,  0.3190],
         [ 1.9128, -0.9402,  1.7932,  2.4108,  0.3863],
         [ 0.9783, -0.0048, -0.5355,  0.4911,  0.6361],
         [-1.3685, -0.7965,  0.1684,  1.4190, -0.4349]]])

Tensor a[1]:
tensor([[-1.2622, -0.8485, -0.2482, -0.6014, -0.3126],
        [-0.2190,  0.9474,  0.7915,  0.4334, -0.5306],
        [ 0.3472,  0.6003, -0.5783,  1.1203, -2.4669],
        [ 0.6066, -1.1424,  0.0438, -0.0313, -0.7336]])

Tensor a[1:, 2:4]:
tensor([[[ 0.3472,  0.6003, -0.5783,  1.1203, -2.4

In [7]:
import torch

a = torch.randn(3, 4)

print("Original:")
print(a)

print("\nFlatten:")
print(a.ravel())

print("\nReshape to 3 x 2 x 2:")
a_reshaped = a.reshape(3, 2, 2)
print(a_reshaped)


print("\nSố phần tử ban đầu:", a.numel())
print("Số phần tử sau khi reshape:", a_reshaped.numel())


a_2x6 = a.reshape(2, 6)
print("\nReshape to 2 x 6:")
print(a_2x6)

Original:
tensor([[ 0.1684, -0.0453,  0.4989,  0.2765],
        [-0.1597,  1.7806,  2.7214, -0.7025],
        [ 0.0528, -0.5753,  0.4396, -0.5767]])

Flatten:
tensor([ 0.1684, -0.0453,  0.4989,  0.2765, -0.1597,  1.7806,  2.7214, -0.7025,
         0.0528, -0.5753,  0.4396, -0.5767])

Reshape to 3 x 2 x 2:
tensor([[[ 0.1684, -0.0453],
         [ 0.4989,  0.2765]],

        [[-0.1597,  1.7806],
         [ 2.7214, -0.7025]],

        [[ 0.0528, -0.5753],
         [ 0.4396, -0.5767]]])

Số phần tử ban đầu: 12
Số phần tử sau khi reshape: 12

Reshape to 2 x 6:
tensor([[ 0.1684, -0.0453,  0.4989,  0.2765, -0.1597,  1.7806],
        [ 2.7214, -0.7025,  0.0528, -0.5753,  0.4396, -0.5767]])


In [9]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)

print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)
print("\nShape của a @ b.T:", (a @ b.T).shape)

a:
tensor([[-1.2293, -0.1203, -0.9881],
        [-0.9671,  0.8639,  1.3496]])
b:
tensor([[ 0.5117,  0.7450, -1.1493],
        [ 0.0081,  0.7830,  0.2662]])

a + b:
tensor([[-0.7176,  0.6247, -2.1374],
        [-0.9590,  1.6469,  1.6158]])

a / b:
tensor([[  -2.4022,   -0.1614,    0.8598],
        [-119.2599,    1.1033,    5.0699]])

a^2:
tensor([[1.5111, 0.0145, 0.9764],
        [0.9353, 0.7463, 1.8214]])

Matrix multiplication:
tensor([[ 0.4170, -0.3672],
        [-1.4023,  1.0279]])

Shape của a @ b.T: torch.Size([2, 2])


In [10]:
import torch

a = torch.randn(3, 4)

print(a)
print("\nMean:")
print(torch.mean(a, dim=1))

print("\nStandard deviation:")
print(torch.std(a, dim=1))

print("\nCumulative sum:")
print(torch.cumsum(a, dim=1))

tensor([[ 0.9378, -0.4190,  0.0082,  0.5337],
        [ 1.3120,  0.4231, -3.1554,  0.2793],
        [ 0.7913, -1.8229, -0.3626,  0.0541]])

Mean:
tensor([ 0.2652, -0.2852, -0.3350])

Standard deviation:
tensor([0.5941, 1.9672, 1.1007])

Cumulative sum:
tensor([[ 0.9378,  0.5188,  0.5269,  1.0606],
        [ 1.3120,  1.7351, -1.4203, -1.1410],
        [ 0.7913, -1.0316, -1.3942, -1.3401]])


In [11]:
import torch

x = torch.tensor(3.6, requires_grad=True)

y = 3 * x**2 + 2 * x + 1

y.backward()

print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(47.0800, grad_fn=<AddBackward0>)
x.grad = tensor(23.6000)


In [12]:
import numpy as np
import torch

polynomial = np.poly1d([1, 2, 3])
N = 20

X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[-1.1499],
        [ 1.1422],
        [ 0.6323]], requires_grad=True)
Learned coefficients:
tensor([[1.0018],
        [2.0048],
        [2.7891]], requires_grad=True)


In [13]:
import random
import torch

A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)

EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)

for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2

    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4

    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()

print("A =", A.item())
print("B =", B.item())
print("C =", C.item())
print("D =", D.item())

print("\nKiểm tra lại 4 phương trình:")
print("A + B =", (A + B).item(), "(Mục tiêu: 9)")
print("C - D =", (C - D).item(), "(Mục tiêu: 1)")
print("A + C =", (A + C).item(), "(Mục tiêu: 8)")
print("B - D =", (B - D).item(), "(Mục tiêu: 2)")

A = 4.656971454620361
B = 4.342984199523926
C = 3.343010902404785
D = 2.3429954051971436

Kiểm tra lại 4 phương trình:
A + B = 8.999956130981445 (Mục tiêu: 9)
C - D = 1.0000154972076416 (Mục tiêu: 1)
A + C = 7.9999823570251465 (Mục tiêu: 8)
B - D = 1.9999887943267822 (Mục tiêu: 2)


In [14]:
import torch

X = torch.arange(24)

X_4x6 = X.reshape(4, 6)
X_2x12 = X.reshape(2, 12)
X_2x3x4 = X.reshape(2, 3, 4)

print("--- Yêu cầu 1 ---")
print("4x6:\n", X_4x6)
print("2x12:\n", X_2x12)
print("2x3x4:\n", X_2x3x4)


A = torch.randn(3, 4)
B = torch.randn(3, 4)

add_res = A + B
mul_res = A * B
div_res = A / B

mean_col_A = torch.mean(A, dim=0)
std_col_A = torch.std(A, dim=0)

mean_col_B = torch.mean(B, dim=0)
std_col_B = torch.std(B, dim=0)

print("\n--- Yêu cầu 2 ---")
print("A + B:\n", add_res)
print("A * B:\n", mul_res)
print("A / B:\n", div_res)
print("Trung bình theo cột A:", mean_col_A)
print("Độ lệch chuẩn theo cột A:", std_col_A)


x = torch.tensor(2.0, requires_grad=True)
y = 2 * x**2 + 5 * x + 3
y.backward()

print("\n--- Yêu cầu 3 ---")
print("dy/dx bằng autograd:", x.grad.item())


import numpy as np

polynomial = np.poly1d([2, -3, 5])
N = 20

X_data = np.random.randn(N, 1) * 5
Y_data = polynomial(X_data)

XX = np.hstack([
    X_data * X_data,
    X_data,
    np.ones_like(X_data)
])

w = torch.randn(3, 1, requires_grad=True)
x_poly = torch.tensor(XX, dtype=torch.float32)
y_poly = torch.tensor(Y_data, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

for epoch in range(1500):
    optimizer.zero_grad()
    y_pred = x_poly @ w
    mse = torch.mean(torch.square(y_poly - y_pred))
    mse.backward()
    optimizer.step()

print("\n--- Yêu cầu 4 ---")
print("Hệ số tìm được (gần với [2, -3, 5]):\n", w.detach().numpy().flatten())

--- Yêu cầu 1 ---
4x6:
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])
2x12:
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
2x3x4:
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

--- Yêu cầu 2 ---
A + B:
 tensor([[ 1.2960,  0.3629, -2.0816, -0.2804],
        [-1.0735, -0.3835, -1.7332, -0.0256],
        [ 1.5706, -0.8883,  0.3523, -0.1178]])
A * B:
 tensor([[-0.0155, -0.3035,  0.8633, -0.0296],
        [ 0.2383, -0.1581, -0.2992, -0.0263],
        [ 0.5312, -0.3781, -0.1934, -0.0010]])
A / B:
 tensor([[-1.1029e+02, -1.9105e+00,  2.6409e+00, -2.2581e-01],
        [ 2.4225e+00, -3.9439e-01, -8.3642e-02, -8.5399e-01],
        [ 4.5733e-01, -3.8257e+00, -2.1834e+00, -1.6255e+01]])
Trung bình theo cột A: tensor([ 0